finished spawn system
Angels-On-Rooftops/Angel-Insolvent pull request #8
Opened 2024-09-10 20:32 UTC by JayDeeThomas

2024-09-10 21:09 UTC, smlendzian commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +        player.transform.position = respawnPoint;
Can replace this line with: this.transform.position = respawnPoint;

2024-09-10 21:10 UTC, smlendzian commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +    GameObject player;
Can remove player object (see comment below where the object can be referenced using this)

2024-09-10 21:10 UTC, smlendzian commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +        player = this.gameObject;
can remove player object (see below)

2024-09-10 21:15 UTC, smlendzian commented on Assets/Scripts/Spawn System/Checkpoint.cs
> +    public Vector3 postion; //spawn location
these should be private
You can create a private serialized field using the syntax [SerializeField] private bool activated

2024-09-10 21:17 UTC, smlendzian commented on Assets/Scripts/Spawn System/Checkpoint.cs
> +    public Vector3 postion; //spawn location
These should be properties

2024-09-10 23:51 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/SpawnPoint.cs
> +}
Probably best to remove this class entirely, and justhave an option to pass an initial checkpoint object into the playerrespawn through a serializefield. I don't think we need the non-revisiting property of this behavior (to my knowledge, the only thing that would functionally change), but if we want that option, adding a toggle for non-revisiting to checkpoint is probably the best way to go about it.

2024-09-10 23:55 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/Checkpoint.cs
> +    [SerializeField] int height = 1; //y position to spawn player at
this should be a Vector3 offset to allow for more dynamic behavior

2024-09-10 23:58 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/Checkpoint.cs
> +        postion = new Vector3(this.transform.position.x, height, this.transform.position.z);
A better implementation would be to do `position = this.transform.position + offset;`, currently the y coordinate is being set in world space which will raise difficulties if the checkpoint isn't at y=0.

2024-09-11 00:00 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +    SpawnPoint spawn;
can change this to a serializefield containing a checkpoint (see recommended changes in SpawnPoint)

2024-09-11 00:01 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +    void Start()
update to non-spawn point using logic (see SpawnPoint for details)

2024-09-11 00:02 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/PlayerRespawn.cs
> +        if (other.gameObject.CompareTag("Respawn")) {
change to 
```
if (!other.gameObject.CompareTag("Respawn")) {
    return;
}
``` to reduce nesting

2024-09-11 00:03 UTC, cadenceblorbo requested changes
See comments for recommended changes to system

2024-09-11 00:05 UTC, cadenceblorbo commented on Assets/Scripts/Spawn System/SpawnPoint.cs
> +}
(this should also make loading saves easier)

2024-09-16 19:25 UTC, merged